// <auto-generated />
using System;
using BetteRFlow.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetteRFlow.Shared.Migrations
{
    [DbContext(typeof(BetteRFlowContext))]
    [Migration("20251228153021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("BetteRFlow.Shared.Models.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdressNyckelÖverlämning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AndrahandsuthyrningAnsökanTill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AndrahandsuthyrningAvgift")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AndrahandsuthyrningKrävergodkännande")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AndrahandsuthyrningVillkorUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AntalGarageplatser")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AntalLaddplatser")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AntalLägenheter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AntalParkeringsplatser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvgiftInnefattarAnnat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AvgiftInnefattarBredband")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvgiftInnefattarHemförsäkring")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvgiftInnefattarKabelTV")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvgiftInnefattarKallvatten")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvgiftInnefattarKällare")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvgiftInnefattarVarmvatten")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvgiftInnefattarVärme")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Barnvagnsförråd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bastu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BeslutOmMedlemskap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BredbandKundservice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bredbandshastighet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bredbandsleverantör")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BrfId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrfNamn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Byggnadsår")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Cykelförråd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DelatÄgande")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EkonomiskFörvaltare")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Elavtal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ElavtalKommentar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ElplintarPåMark")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Energideklaration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnergideklarationDatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraLokaler")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraLokalerKommentar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fastighet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FastighetsFörvaltare")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Festlokal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FriHöjdGarage")
                        .HasColumnType("TEXT");

                    b.Property<string>("GemensammaUtrymmennAnnat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Gym")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Gästlägenhet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hemsida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("JuridiskPersonFårFörvärva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JuridiskPersonKommentar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KontaktEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KontaktTelefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("KostnadGarageplats")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("KostnadGarageplatsElektricitet")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("KostnadParkeringsplats")
                        .HasColumnType("TEXT");

                    b.Property<string>("Laddkostnad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedlemsansökanSkickasTill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedlemskapsRutin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinstaAndel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NyckelÖverlämning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Organisationsnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParkeringKontakt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanerardeReparationer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenasteAvgiftsförändring")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StädningGemensamma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tvättstuga")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uppvärmning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VadSkasÖverlämnas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ventilation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ÄktaBrf")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Överlåtelseavgift")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrfId");

                    b.HasIndex("UserId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.FormSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdressNyckelÖverlämning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AndrahandsuthyrningAnsökanTill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AndrahandsuthyrningAvgift")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AndrahandsuthyrningKrävergodkännande")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AndrahandsuthyrningVillkorUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AntalGarageplatser")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AntalLaddplatser")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AntalLägenheter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AntalParkeringsplatser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvgiftInnefattarAnnat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AvgiftInnefattarBredband")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvgiftInnefattarHemförsäkring")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvgiftInnefattarKabelTV")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvgiftInnefattarKallvatten")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvgiftInnefattarKällare")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvgiftInnefattarVarmvatten")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvgiftInnefattarVärme")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Barnvagnsförråd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bastu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BeslutOmMedlemskap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BredbandKundservice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bredbandshastighet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bredbandsleverantör")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BrfId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrfNamn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Byggnadsår")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cykelförråd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DelatÄgande")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EkonomiskFörvaltare")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Elavtal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ElavtalKommentar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ElplintarPåMark")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Energideklaration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnergideklarationDatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraLokaler")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraLokalerKommentar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fastighet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FastighetsFörvaltare")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Festlokal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FriHöjdGarage")
                        .HasColumnType("TEXT");

                    b.Property<string>("GemensammaUtrymmennAnnat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Gym")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Gästlägenhet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hemsida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("JuridiskPersonFårFörvärva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JuridiskPersonKommentar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KontaktEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KontaktTelefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("KostnadGarageplats")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("KostnadGarageplatsElektricitet")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("KostnadParkeringsplats")
                        .HasColumnType("TEXT");

                    b.Property<string>("Laddkostnad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedlemsansökanSkickasTill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedlemskapsRutin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinstaAndel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NyckelÖverlämning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Organisationsnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParkeringKontakt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanerardeReparationer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenasteAvgiftsförändring")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StädningGemensamma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tvättstuga")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uppvärmning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VadSkasÖverlämnas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ventilation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ÄktaBrf")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Överlåtelseavgift")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrfId");

                    b.ToTable("FormSubmissions");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormSubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormSubmissionId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.Realtor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuinessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Realtor");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrfId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Firma")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fornamn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RealtorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrfId");

                    b.HasIndex("RealtorId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Brf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gatuadress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hemsida")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KontaktEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KontaktTelefon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationsNummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brfs");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.Form", b =>
                {
                    b.HasOne("Brf", "Brf")
                        .WithMany()
                        .HasForeignKey("BrfId");

                    b.HasOne("BetteRFlow.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brf");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.FormSubmission", b =>
                {
                    b.HasOne("Brf", "Brf")
                        .WithMany("FormSubmissions")
                        .HasForeignKey("BrfId");

                    b.Navigation("Brf");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.Purchase", b =>
                {
                    b.HasOne("BetteRFlow.Shared.Models.FormSubmission", "FormSubmission")
                        .WithMany()
                        .HasForeignKey("FormSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetteRFlow.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormSubmission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.User", b =>
                {
                    b.HasOne("Brf", "Brf")
                        .WithMany()
                        .HasForeignKey("BrfId");

                    b.HasOne("BetteRFlow.Shared.Models.Realtor", "Realtor")
                        .WithMany()
                        .HasForeignKey("RealtorId");

                    b.Navigation("Brf");

                    b.Navigation("Realtor");
                });

            modelBuilder.Entity("Brf", b =>
                {
                    b.Navigation("FormSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
