// <auto-generated />
using System;
using BetteRFlow.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetteRFlow.Shared.Migrations
{
    [DbContext(typeof(BetteRFlowContext))]
    partial class BetteRFlowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("BetteRFlow.Shared.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.Fastighet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrfId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("BrfId");

                    b.ToTable("Fastigheter");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.Form", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.FormSubmission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("FormSubmissions");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.Invitation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.Purchase", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.PurchaseFastighet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("PurchaseFastigheter");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.Realtor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuinessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Realtors");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrfId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Firma")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fornamn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RealtorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrfId");

                    b.HasIndex("RealtorId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Brf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hemsida")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KontaktEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KontaktTelefon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationsAdress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationsNummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brfs");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.Fastighet", b =>
                {
                    b.HasOne("Brf", null)
                        .WithMany("Fastigheter")
                        .HasForeignKey("BrfId");
                });

            modelBuilder.Entity("BetteRFlow.Shared.Models.User", b =>
                {
                    b.HasOne("Brf", "Brf")
                        .WithMany()
                        .HasForeignKey("BrfId");

                    b.HasOne("BetteRFlow.Shared.Models.Realtor", "Realtor")
                        .WithMany()
                        .HasForeignKey("RealtorId");

                    b.Navigation("Brf");

                    b.Navigation("Realtor");
                });

            modelBuilder.Entity("Brf", b =>
                {
                    b.Navigation("Fastigheter");
                });
#pragma warning restore 612, 618
        }
    }
}
